//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS4B
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SMS4B", ConfigurationName="SMS4B.WSSMSoap")]
    public interface WSSMSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/StartSessionUTC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> StartSessionUTCAsync(string Login, string Password, string Local);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/StartSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long> StartSessionAsync(string Login, string Password, short Gmt);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/CancelGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> CancelGroupAsync(long SessionID, long Group);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/CloseSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> CloseSessionAsync(long SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/GroupSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SMS4B.GroupSMSResponse> GroupSMSAsync(SMS4B.GroupSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/CheckSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SMS4B.CheckSMSResult> CheckSMSAsync(long SessionId, string[] Guids);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/LoadSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SMS4B.LoadSMSResult> LoadSMSAsync(long SessionId, string ChangesFrom, int Flags);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/ParamSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SMS4B.ParamSMSResult> ParamSMSAsync(long SessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SendSMSAsync(string Login, string Password, string Source, long Phone, string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/GetInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="SMS4B/StatusSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> StatusSMSAsync(string Login, string Password, string MessageId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SMS4B")]
    public partial class GroupSMSList
    {
        
        private string gField;
        
        private string dField;
        
        private string bField;
        
        private int eField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SMS4B")]
    public partial class ParamSMSResult
    {
        
        private int resultField;
        
        private double restField;
        
        private string addressesField;
        
        private long addrMaskField;
        
        private string uTCField;
        
        private int durationField;
        
        private int limitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Rest
        {
            get
            {
                return this.restField;
            }
            set
            {
                this.restField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long AddrMask
        {
            get
            {
                return this.addrMaskField;
            }
            set
            {
                this.addrMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UTC
        {
            get
            {
                return this.uTCField;
            }
            set
            {
                this.uTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SMS4B")]
    public partial class SMSList
    {
        
        private string gField;
        
        private string dField;
        
        private string bField;
        
        private int eField;
        
        private int aField;
        
        private int pField;
        
        private string mField;
        
        private string tField;
        
        private string sField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int P
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string M
        {
            get
            {
                return this.mField;
            }
            set
            {
                this.mField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string S
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SMS4B")]
    public partial class LoadSMSResult
    {
        
        private int resultField;
        
        private SMSList[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SMSList[] List
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SMS4B")]
    public partial class CheckSMSResult
    {
        
        private int resultField;
        
        private CheckSMSList[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CheckSMSList[] List
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SMS4B")]
    public partial class CheckSMSList
    {
        
        private string gField;
        
        private int rField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int R
        {
            get
            {
                return this.rField;
            }
            set
            {
                this.rField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SMS4B")]
    public partial class GroupSMSResult
    {
        
        private int resultField;
        
        private long groupField;
        
        private CheckSMSList[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CheckSMSList[] List
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupSMS", WrapperNamespace="SMS4B", IsWrapped=true)]
    public partial class GroupSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=0)]
        public long SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=1)]
        public long Group;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=2)]
        public string Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=3)]
        public int Encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=4)]
        public string Body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=5)]
        public string Off;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=6)]
        public string Start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=7)]
        public string Period;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SMS4B.GroupSMSList[] List;
        
        public GroupSMSRequest()
        {
        }
        
        public GroupSMSRequest(long SessionId, long Group, string Source, int Encoding, string Body, string Off, string Start, string Period, SMS4B.GroupSMSList[] List)
        {
            this.SessionId = SessionId;
            this.Group = Group;
            this.Source = Source;
            this.Encoding = Encoding;
            this.Body = Body;
            this.Off = Off;
            this.Start = Start;
            this.Period = Period;
            this.List = List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupSMSResponse", WrapperNamespace="SMS4B", IsWrapped=true)]
    public partial class GroupSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS4B", Order=0)]
        public SMS4B.GroupSMSResult GroupSMSResult;
        
        public GroupSMSResponse()
        {
        }
        
        public GroupSMSResponse(SMS4B.GroupSMSResult GroupSMSResult)
        {
            this.GroupSMSResult = GroupSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface WSSMSoapChannel : SMS4B.WSSMSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class WSSMSoapClient : System.ServiceModel.ClientBase<SMS4B.WSSMSoap>, SMS4B.WSSMSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSSMSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSSMSoapClient.GetBindingForEndpoint(endpointConfiguration), WSSMSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSMSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSSMSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSMSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSSMSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> StartSessionUTCAsync(string Login, string Password, string Local)
        {
            return base.Channel.StartSessionUTCAsync(Login, Password, Local);
        }
        
        public System.Threading.Tasks.Task<long> StartSessionAsync(string Login, string Password, short Gmt)
        {
            return base.Channel.StartSessionAsync(Login, Password, Gmt);
        }
        
        public System.Threading.Tasks.Task<int> CancelGroupAsync(long SessionID, long Group)
        {
            return base.Channel.CancelGroupAsync(SessionID, Group);
        }
        
        public System.Threading.Tasks.Task<int> CloseSessionAsync(long SessionID)
        {
            return base.Channel.CloseSessionAsync(SessionID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS4B.GroupSMSResponse> SMS4B.WSSMSoap.GroupSMSAsync(SMS4B.GroupSMSRequest request)
        {
            return base.Channel.GroupSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS4B.GroupSMSResponse> GroupSMSAsync(long SessionId, long Group, string Source, int Encoding, string Body, string Off, string Start, string Period, SMS4B.GroupSMSList[] List)
        {
            SMS4B.GroupSMSRequest inValue = new SMS4B.GroupSMSRequest();
            inValue.SessionId = SessionId;
            inValue.Group = Group;
            inValue.Source = Source;
            inValue.Encoding = Encoding;
            inValue.Body = Body;
            inValue.Off = Off;
            inValue.Start = Start;
            inValue.Period = Period;
            inValue.List = List;
            return ((SMS4B.WSSMSoap)(this)).GroupSMSAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<SMS4B.CheckSMSResult> CheckSMSAsync(long SessionId, string[] Guids)
        {
            return base.Channel.CheckSMSAsync(SessionId, Guids);
        }
        
        public System.Threading.Tasks.Task<SMS4B.LoadSMSResult> LoadSMSAsync(long SessionId, string ChangesFrom, int Flags)
        {
            return base.Channel.LoadSMSAsync(SessionId, ChangesFrom, Flags);
        }
        
        public System.Threading.Tasks.Task<SMS4B.ParamSMSResult> ParamSMSAsync(long SessionId)
        {
            return base.Channel.ParamSMSAsync(SessionId);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSAsync(string Login, string Password, string Source, long Phone, string Text)
        {
            return base.Channel.SendSMSAsync(Login, Password, Source, Phone, Text);
        }
        
        public System.Threading.Tasks.Task<string> GetInfoAsync()
        {
            return base.Channel.GetInfoAsync();
        }
        
        public System.Threading.Tasks.Task<string> StatusSMSAsync(string Login, string Password, string MessageId)
        {
            return base.Channel.StatusSMSAsync(Login, Password, MessageId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSSMSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSSMSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSSMSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://sms4b.ru/ws/sms.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSSMSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://sms4b.ru/ws/sms.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSSMSoap,
            
            WSSMSoap12,
        }
    }
}
